### PR TITLE
fix: restore all events in OpenEdxEventsTestMixin.tearDownClass

### PR DESCRIPTION
**Pull request by feanil**
## Summary

`OpenEdxEventsTestMixin.setUpClass()` disables all OpenEdX events then enables only those in `ENABLED_OPENEDX_EVENTS`, but had no `tearDownClass` to restore event state. This meant that after any test class using this mixin completed, all events not in `ENABLED_OPENEDX_EVENTS` remained globally disabled for the remainder of the process.

This was discovered in openedx-platform when shard rebalancing caused `lms/djangoapps/certificates/` and `lms/djangoapps/discussion/django_comment_client/` to run in the same process for the first time. Nine certificate test classes with `ENABLED_OPENEDX_EVENTS = []` left all events disabled, causing `ForumEventTestCase.test_comment_event` to fail with:

```
AttributeError: 'NoneType' object has no attribute 'kwargs'
```

because `FORUM_RESPONSE_COMMENT_CREATED` was never fired (it had been disabled).

## Fix

* Add `tearDownClass` to `OpenEdxEventsTestMixin` that calls `enable_all_events()`, mirroring the disable in 
`setUpClass`. This is consistent with the pattern already used by `FreezeSignalCacheMixin` in the same file.
* This also fixes a bug introduced in https://github.com/openedx/openedx-events/pull/557 which will break `openedx-platform` when it's released. See the refactor commit message for more details.

### CODE REVIEW

**Review by mariajgrimaldi — APPROVED** [review]
Thanks a lot!

**Comment by mariajgrimaldi** [comment]
https://github.com/openedx/openedx-events/releases/tag/v11.1.1 🥇
